version: '3.8'

services:
  db:
    image: postgres:15
    ports:
      - "5432:5432" # Exposes PostgreSQL on port 5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persists database data

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge 